name: Die Sozietät
favicon: null
layout_spectrum: 0.7784275615122169
typography_spectrum: 0.3099363634828478
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.09456600900739431
  lightness: 0.9789199011866003
  saturation: 0.8157466088887304
  rhythmicContrast: 0.9688955892343074
purpose: []
